spring:
  security:
    oauth2:
      resourceserver:
        jwt.public-key-location: classpath:local-public-key.pub

server:
  shutdown: immediate

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0
