# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

generic-service:
  ingress:
    host: token-verification-api-preprod.prison.service.justice.gov.uk

  env:
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "http://hmpps-auth.hmpps-auth-preprod.svc.cluster.local/auth/.well-known/jwks.json"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
