# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: quay.io/hmpps/token-verification-api
  tag: latest
  port: 8080
  livenessProbePath: /health/liveness
  readinessProbePath: /health/readiness

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: token-verification-api.prison.service.justice.gov.uk
      cert_secret: token-verification-api-cert
  path: /

env:
  JAVA_OPTS: "-Xmx512m"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "https://sign-in.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json"
