# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: quay.io/hmpps/token-verification-api
  tag: latest
  pullPolicy: Always
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: token-verification-api.prison.service.justice.gov.uk
      cert_secret: token-verification-api-cert
  path: /

env:
  JAVA_OPTS: "-Xmx512m"
