apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.image.port }}
      name: http
  selector:
    app: {{ template "app.name" . }}
    release: {{ .Release.Name }}
